export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_CONFIRM_TOKEN_REQUEST = 'USER_CONFIRM_TOKEN_REQUEST'
export const USER_CONFIRM_TOKEN_SUCCESS = 'USER_CONFIRM_TOKEN_SUCCESS'
export const USER_CONFIRM_TOKEN_FAILURE = 'USER_CONFIRM_TOKEN_FAILURE'
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const RESET_FORM_STATE = 'RESET_FORM_STATE'

// pagination
export const SET_PAGE = 'SET_PAGE'
// TODOS

export const FETCH_TODOS_BY_USER_REQUEST = 'FETCH_TODOS_BY_USER_REQUEST'
export const FETCH_TODOS_BY_USER_SUCCESS = 'FETCH_TODOS_BY_USER_SUCCESS'
export const FETCH_TODOS_BY_USER_FAILURE = 'FETCH_TODOS_BY_USER_FAILURE'

export const ADD_TODO_BY_USER_REQUEST = 'ADD_TODO_BY_USER_REQUEST'
export const ADD_TODO_BY_USER_SUCCESS = 'ADD_TODO_BY_USER_SUCCESS'
export const ADD_TODO_BY_USER_FAILURE = 'ADD_TODO_BY_USER_FAILURE'

export const EDIT_TODO_TEXT_REQUEST = 'EDIT_TODO_TEXT_REQUEST'
export const EDIT_TODO_TEXT_SUCCESS = 'EDIT_TODO_TEXT_SUCCESS'
export const EDIT_TODO_TEXT_FAILURE = 'EDIT_TODO_TEXT_FAILURE'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

export const TOGGLE_TODO_COMPLETE_BY_USER_REQUEST = 'TOGGLE_TODO_COMPLETE_BY_USER_REQUEST'
export const TOGGLE_TODO_COMPLETE_BY_USER_SUCCESS = 'TOGGLE_TODO_COMPLETE_BY_USER_SUCCESS'
export const TOGGLE_TODO_COMPLETE_BY_USER_FAILURE = 'TOGGLE_TODO_COMPLETE_BY_USER_FAILURE'

export const TOGGLE_ALL_REQUEST = 'TOGGLE_ALL_REQUEST'
export const TOGGLE_ALL_SUCCESS = 'TOGGLE_ALL_SUCCESS'
export const TOGGLE_ALL_FAILURE = 'TOGGLE_ALL_FAILURE'
