export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'
export const RESET_FORM_STATE = 'RESET_FORM_STATE'