export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_CONFIRM_TOKEN_REQUEST = 'USER_CONFIRM_TOKEN_REQUEST'
export const USER_CONFIRM_TOKEN_SUCCESS = 'USER_CONFIRM_TOKEN_SUCCESS'
export const USER_CONFIRM_TOKEN_FAILURE = 'USER_CONFIRM_TOKEN_FAILURE'
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const RESET_FORM_STATE = 'RESET_FORM_STATE'

// TODOS

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE'

export const DELETE_TODO_REQUEST = 'DELETE_TODOS_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODOS_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODOS_FAILURE'

export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST'
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS'
export const TOGGLE_TODO_FAILURE = 'TOGGLE_TODO_FAILURE'